workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -exec dir "{}" \;
          cd ios && pod install
      - name: Build iOS IPA
        script: |
          # WARNING: To generate a valid signed IPA, you must configure your
          # Apple Developer Certificate and Provisioning Profile in the Codemagic Dashboard.
          # If no signing is detected, we use --no-codesign for validity check.
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      - *.dsym.zip
