import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('es'));
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'app_title': 'IMPERIODEV',
      'greeting': 'Hola 👋',
      'share_msg_greeting': 'Hola',
      'share_msg_body': 'aquí te comparto la %s %s por un total de %s', // %s: Type, Folio, Total
      'dashboard_subtitle': 'Aquí está tu resumen de ventas.',
      'total_sales': 'Ventas Totales',
      'notes_created': 'Notas Creadas',
      'create_note_button': 'Nueva Cotización',
      'create_note_subtitle': 'Crear una nueva nota de venta',
      'recent_notes': 'Notas Recientes',
      'no_notes': 'No hay notas creadas aún.',
      'settings_title': 'Ajustes',
      'client_title': 'Clientes',
      'home_title': 'Inicio',
      'notes_title': 'Notas',
      'about_title': 'Acerca de',
      'theme_title': 'Tema Oscuro',
      'lang_title': 'Idioma',
      'export_title': 'Exportar Notas (ZIP)',
      'version': 'Versión',
      'developed_by': 'Desarrollado por ImperioDev',
      'client_name_hint': 'Nombre del Cliente / Empresa',
      'contact_hint': 'Contacto (Email/WhatsApp)',
      'save_draft': 'Borrador',
      'generate_send': 'Generar y Enviar',
      'add_item': 'Añadir Item',
      'add_service': 'Agregar otro servicio',
      'subtotal': 'Subtotal',
      'total': 'Total',
      'additional_notes': 'Notas Adicionales',
      'delete_note': 'Eliminar',
      'view_pdf': 'Ver PDF',
      'edit_note': 'Editar',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'save': 'Guardar',
      'export_success': 'Respaldo generado correctamente',
      'export_no_notes': 'No hay notas pendientes para exportar',
      'search_client': 'Buscar cliente...',
      'clients_empty': 'No hay clientes registrados',
      'add_client': 'Añadir Cliente',
      'client_name': 'Nombre Completo',
      'client_email': 'Correo Electrónico',
      'client_phone': 'Teléfono',
      'client_address': 'Dirección',
      'create_note_for': 'Crear Nota',
      'view_history': 'Ver Historial',
      'delete_client_title': '¿Eliminar cliente?',
      'delete_client_msg': 'Esta acción no se puede deshacer.',
      'preview_title': 'Vista Previa',
      'preview_subtitle': 'Vista previa del documento PDF',
      'whatsapp': 'WhatsApp',
      'share_msg_start': 'Hola',
      'share_msg_end': 'aquí te comparto la cotización',
      'saved_to': 'Guardado en',
      'share_file': 'Compartir',
      'save_device': 'Guardar en dispositivo',
      'client_deleted': 'Cliente eliminado',
      'draft_saved': 'Guardado en borradores',
      'add_service_error': 'Agregue al menos un servicio',
      'hint_client_name': 'Ej. Empresa S.A.',
      'hint_contact': 'contacto@empresa.com',
      'hint_desc': 'Descripción del servicio',
      'hint_additional': 'Detalles de pago, tiempos de entrega...',
      'stat_total_sales': 'Ventas Totales',
      'stat_notes_created': 'Notas Creadas',
      'section_client': 'Cliente',
      'section_services': 'Servicios',
      'section_summary': 'Resumen',
      'pdf_view': 'Ver PDF',
      'pdf_quote': 'COTIZACIÓN',
      'pdf_prepared_for': 'PREPARADO PARA',
      'pdf_concept': 'CONCEPTO',
      'pdf_quantity': 'Cantidad',
      'pdf_unit': 'Unit',
      'pdf_additional_notes': 'NOTAS ADICIONALES',
      'pdf_footer': 'Esta cotización es válida por 15 días. Gracias por confiar en ImperioDev.',
      'status_completed': 'COMPLETADA',
      'status_draft': 'BORRADOR',
      'menu_view_pdf': 'Ver PDF',
      'menu_edit': 'Editar',
      'menu_delete': 'Eliminar',
      'my_notes': 'Mis Notas',
      'add_another_service': 'Agregar otro servicio',
      'no_services_added': 'No hay servicios añadidos',
      'label_date': 'Fecha',
      'label_folio': 'Folio',
      'label_contact': 'Contacto (Email/WhatsApp)',
      'label_vat': 'IVA',
      'remove_item': 'Eliminar',
      'label_quantity': 'CANT.',
      'label_unit_price': 'PRECIO UNITARIO',
      'note_type_quote': 'Cotización',
      'note_type_sale': 'Nota de Venta',
      'label_phone': 'Teléfono',
      'label_email': 'Correo',
      'whatsapp_error_no_phone': 'No se agregó número telefónico del cliente',
      'edit_client': 'Editar Cliente',
      'client_details_updated': 'Detalles del cliente actualizados',
      'filename_quote': 'cotizacion',
      'filename_sale': 'nota_de_venta',
      'label_payment_method': 'Método de Pago',
      'hint_payment_method': 'Ej. Transferencia Interbancaria',
      'selected_count': '%s Seleccionadas',
      'tooltip_select_all': 'Seleccionar Todas',
      'tooltip_select': 'Seleccionar',
      'delete_notes_title': 'Eliminar Notas',
      'delete_notes_msg': '¿Estás seguro de eliminar %s notas seleccionadas?',
    },
    'en': {
      'app_title': 'IMPERIODEV',
      'greeting': 'Hello 👋',
      'share_msg_greeting': 'Hello',
      'share_msg_body': 'here is the %s %s for a total of %s',
      'dashboard_subtitle': 'Here is your sales summary.',
      'total_sales': 'Total Sales',
      'notes_created': 'Notes Created',
      'create_note_button': 'New Quote',
      'create_note_subtitle': 'Create a new sales note',
      'recent_notes': 'Recent Notes',
      'no_notes': 'No notes created yet.',
      'settings_title': 'Settings',
      'client_title': 'Clients',
      'home_title': 'Home',
      'notes_title': 'Notes',
      'about_title': 'About',
      'theme_title': 'Dark Mode',
      'lang_title': 'Language',
      'export_title': 'Export Notes (ZIP)',
      'version': 'Version',
      'developed_by': 'Developed by ImperioDev',
      'client_name_hint': 'Client Name / Company',
      'contact_hint': 'Contact (Email/WhatsApp)',
      'save_draft': 'Draft',
      'generate_send': 'Generate & Send',
      'add_item': 'Add Item',
      'add_service': 'Add another service',
      'subtotal': 'Subtotal',
      'total': 'Total',
      'additional_notes': 'Additional Notes',
      'delete_note': 'Delete',
      'view_pdf': 'View PDF',
      'edit_note': 'Edit',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'save': 'Save',
      'export_success': 'Backup generated successfully',
      'export_no_notes': 'No completed notes to export',
      'search_client': 'Search client...',
      'clients_empty': 'No clients registered',
      'add_client': 'Add Client',
      'client_name': 'Full Name',
      'client_email': 'Email',
      'client_phone': 'Phone',
      'client_address': 'Address',
      'create_note_for': 'Create Note',
      'view_history': 'View History',
      'delete_client_title': 'Delete client?',
      'delete_client_msg': 'This action cannot be undone.',
      'preview_title': 'Preview',
      'preview_subtitle': 'PDF Document Preview',
      'whatsapp': 'WhatsApp',
      'share_msg_start': 'Hello',
      'share_msg_end': 'here is the quote',
      'saved_to': 'Saved to',
      'share_file': 'Share',
      'save_device': 'Save to device',
      'client_deleted': 'Client deleted',
      'draft_saved': 'Saved to drafts',
      'add_service_error': 'Please add at least one service',
      'hint_client_name': 'Ex. Company Inc.',
      'hint_contact': 'contact@company.com',
      'hint_desc': 'Service description',
      'hint_additional': 'Payment details, delivery time...',
      'stat_total_sales': 'Total Sales',
      'stat_notes_created': 'Notes Created',
      'section_client': 'Client',
      'section_services': 'Services',
      'section_summary': 'Summary',
      'pdf_view': 'View PDF',
      'pdf_quote': 'QUOTE',
      'pdf_prepared_for': 'PREPARED FOR',
      'pdf_concept': 'CONCEPT',
      'pdf_quantity': 'Quantity',
      'pdf_unit': 'Unit',
      'pdf_additional_notes': 'ADDITIONAL NOTES',
      'pdf_footer': 'This quote is valid for 15 days. Thank you for trusting ImperioDev.',
      'status_completed': 'COMPLETED',
      'status_draft': 'DRAFT',
      'menu_view_pdf': 'View PDF',
      'menu_edit': 'Edit',
      'menu_delete': 'Delete',
      'my_notes': 'My Notes',
      'add_another_service': 'Add another service',
      'no_services_added': 'No services added',
      'label_date': 'Date',
      'label_folio': 'Folio',
      'label_contact': 'Contact (Email/WhatsApp)',
      'label_vat': 'VAT',
      'remove_item': 'Remove',
      'label_quantity': 'QTY',
      'label_unit_price': 'UNIT PRICE',
      'note_type_quote': 'Quote',
      'note_type_sale': 'Sales Note',
      'label_phone': 'Phone',
      'label_email': 'Email',
      'whatsapp_error_no_phone': 'Client phone number missing',
      'edit_client': 'Edit Client',
      'client_details_updated': 'Client details updated',
      'filename_quote': 'quote',
      'filename_sale': 'sales_note',
      'label_payment_method': 'Payment Method',
      'hint_payment_method': 'Ex. Bank Transfer',
      'selected_count': '%s Selected',
      'tooltip_select_all': 'Select All',
      'tooltip_select': 'Select',
      'delete_notes_title': 'Delete Notes',
      'delete_notes_msg': 'Are you sure you want to delete %s selected notes?',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['es', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
